# Base Settings

## Library

In [25]:
# Library import

## pandas
import pandas as pd


## numpy
import numpy as np
from numpy import linalg

## matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib.patches as mpatches
from matplotlib import cm
from matplotlib.ticker import LinearLocator


## scipy
from scipy import stats
from scipy.stats import skew, kurtosis
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.cluster.hierarchy import cut_tree
from scipy.misc import derivative

## statsmodels
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.graphics.factorplots import interaction_plot

## scikit-learn
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans


import missingno as msno
import urllib
import re
import random
import seaborn as sns
import math
from openpyxl import load_workbook
from datetime import datetime


import sympy
# Juypter 노트북에서 수학식의 LaTeX 표현을 위해 필요함
sympy.init_printing(use_latex='mathjax')


# from vega_datasets import data
# from tabulate import tabulate

#ignore warnings
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

## Google Drive

In [26]:
# Google drive mout
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Path

In [27]:
# 경로 설정
# 기본 디렉토리 경로지정
path_base = '/content/drive/Shareddrives/coding/AIB17/Section1/AIB_section1_project/'

# 데이터 디렉토리 경로지정
path_data = path_base + 'data/'

# 결과 디렉토리 경로지정
path_results = path_base + 'results/'

## 기타 설정

In [28]:
# 그래프 한글폰트 개선
# plt.rcParams['font.family'] ='Malgun Gothic'
# plt.rcParams['axes.unicode_minus'] =False
# plt.rc('font', family='NanumGothic')

In [29]:
# 그래프 한글폰트 개선
# !apt -qq -y install fonts-nanum > /dev/null
 
# fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
# font = fm.FontProperties(fname=fontpath, size=10)
# fm._rebuild()
 
# # 그래프에 retina display 적용
# %config InlineBackend.figure_format = 'retina'
 
# # Colab 의 한글 폰트 설정
# plt.rc('font', family='NanumBarunGothic') 

In [30]:
plt.style.use('seaborn')
# plt.style.use('default')
# sns.set(font_scale=1)

# pandas loat format 설정
# pd.options.display.float_format = None                  # float 포멧 초기화
pd.options.display.float_format = '{:.2f}'.format      # 소수점 둘째자리까지 표시
# pd.options.display.float_format = '{:,.2f}'.format      # 천단위 콤마찍고, 소수점 둘째자리까지 표시

# 10

다음 조건에서 Type-I Error가 발생하는 경우는 어떤 것인가요?
🔎 보기)

최근 실시한 조사에 따르면 국가 A의 실업률이 4%라고 합니다. 
국가 A의 한 도시에서, 도시의 시장은 이 실업률이 자신의 도시에게도 똑같은지 살펴보려 합니다. 
시장은 표본을 모아서 실업률이 4%보다 유의미하게 높은지 알아보고자 합니다.

이 때, p는 도시의 실업률입니다. 
이 실험의 가설은 아래와 같습니다.

H_0 : p = 0.04
H_a : p ≠ 0.04

📌 귀무가설과 대립가설을
H_0 : p =< 0.04
H_a : p > 0.04
으로 설정하는 것이 더 적절하지 않을까?

# 12

In [31]:
# 사전확률 : 암에 걸릴 확률 1%
# P(C) = 0.01  
prio = 0.01 

# 데이터
# 암 검사가 정확히 암을 양성이라고 진단할 확률은 90%
# P(Pr | C) = 0.9
pos_prob = 0.9

# 암이 아닌데 양성이라고 진단할 확률은 10%
# P(Pr | ^C) = 0.1
nag_prob = 0.1

# 사후확률
# P(C | Pr) = P(Pr ⋂ C) / P(Pr)
#          = (P(Pr | C) * P(C)) / P(Pr)
#          = (P(Pr | C) * P(C)) / P(Pr ⋂ C) + P(Pr ⋂ ^C)
#          = (P(Pr | C) * P(C)) / P(Pr | C) * P(C) + P(Pr | ^C) * (1 - P(C))

post_prob = (pos_prob * prio) / (pos_prob * prio + nag_prob * (1 - prio))
print('%.3f'%(post_prob))

0.083


# 13
다음 중 보기에 대해 옳지 않은 설명을 고르세요.

🔎 보기)

뺑소니 사건이 발생했습니다. 목격자의 진술에 의하면, 용의차량은 빨간색 차량이라고 합니다. 
해당 지역의 차량은 빨강과 파랑 두 가지로, 전체 차량 중 빨간색 차량의 비율은 20%, 파란색 차량의 비율은 80%를 차지합니다. 

목격자 증언을 검증하기 위해, 사건현장과 비슷한 환경을 구성하여 모의실험을 진행했습니다. 
이때, 실제 빨간색 차량을 빨강이라고 정확히 증언한 비율은 60%로 밝혀졌습니다. 
경찰 측에서는 목격자가 차량의 색을 정확히 증언했을 때, 그 차량이 빨간색 차량일 확률을 알고자 합니다.

(용의차량이 실제로 빨간색 차량일 사건을 R, 용의차량이 실제로 파란색 차량일 사건을 B, 
  목격자가 차량의 색을 정확히 증언하는 사건을 A 라고 정의합니다.)

📌 문제에서...
"용의차량이 실제로 빨간색 차량일 사건을 R"라는 표현이 사전확률을 의미하는지, 사후확률을 의미하는지

In [32]:
# 사전확률 : 전체 차량 중 빨간색 차량의 비율은 20%, 파란색 차량의 비율은 80%
# P(C) = 0.2  
prio = 0.2 

# 데이터
# 암 검사가 정확히 암을 양성이라고 진단할 확률은 90%
# P(Pr | C) = 0.9
pos_prob = 0.9

# 암이 아닌데 양성이라고 진단할 확률은 10%
# P(Pr | ^C) = 0.1
nag_prob = 0.1

# 사후확률
# P(C | Pr) = P(Pr ⋂ C) / P(Pr)
#          = (P(Pr | C) * P(C)) / P(Pr)
#          = (P(Pr | C) * P(C)) / P(Pr ⋂ C) + P(Pr ⋂ ^C)
#          = (P(Pr | C) * P(C)) / P(Pr | C) * P(C) + P(Pr | ^C) * (1 - P(C))

post_prob = (pos_prob * prio) / (pos_prob * prio + nag_prob * (1 - prio))
print('%.3f'%(post_prob))

0.692


# 14

In [33]:
arr_a = np.array([[20,2],
                 [135,1]])
arr_a

array([[ 20,   2],
       [135,   1]])

In [34]:
arr_b = np.array([[3,7,20],
                 [6,14,1],
                  [9,21,1]])
arr_b

array([[ 3,  7, 20],
       [ 6, 14,  1],
       [ 9, 21,  1]])

In [35]:
np.linalg.det(arr_b)

0.0

In [36]:
np.linalg.det(arr_a)

-250.0000000000001

# 16

In [37]:
arr_c = np.array([[4,2],
                 [2,4]])
arr_c

array([[4, 2],
       [2, 4]])

In [38]:
eigenstuff = np.linalg.eig(arr_c)
eigenstuff

(array([6., 2.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [40]:
def f_def(x):
    return x**3 + x**2 - 10*x + 3

print('🎈 답 🎈\n%.0f'%(derivative(f_def, 1, dx=1e-5)))

🎈 답 🎈
-5
